project:
  type: website
  output-dir: docs

website:
  title: "Angus Robertson"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: projects.qmd
        text: Projects
      - href: publications.qmd
        text: Publications
      - href: teaching.qmd
        text: Teaching
      - cv.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



