project:
  type: website
  output-dir: docs

website:
  title: "Angus Robertson"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: publications.qmd
        text: Publications

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



