---
title: "CV"
---


Angus is a postdoctoral researcher in the Division of Biophysical Chemistry at the Center for Molecular Protein Sciences [(CMPS)](https://www.cmps.lu.se), Lund University, Sweden. 

### Current Position(s) 
* 2022-present - Postdoctoral researcher, [Akke group](https://www.cmps.lu.se/bpc/research/akke/)
	+ Biophysical Chemistry, Center for Molecular Protein Science, Lund University, Sweden

### Previous Position(s) 
* 2019-2022 - Postdoctoral researcher, [Bax group](https://spin.niddk.nih.gov/bax/)
    + Laboratory of Chemical Physics, National Institutes of Diabetes and Digestive and Kidney Disease (NIDDK), National Institutes of Health (NIH), U.S.A.

### Education
* 2014-2018	- PhD in Biomolecular NMR, [Waltho group](https://www.sheffield.ac.uk/biosciences/people/academic-staff/jon-waltho)
	+ Department of Molecular Biology and Biotechnology (School of Biosciences), Sheffield, U.K.
	+ Prof. Jon Waltho

* 2011-2014	- BSc in Biochemistry (First Class Honors)
	+ Department of Molecular Biology and Biotechnology (School of Biosciences), Sheffield, U.K.

### Awards
* 2023-2025 - Marie Skłodowska-Curie Actions Postdoctoral Fellowship (MSCA-PF)
* 2024-2028 - Swedish Research Council (VR) Starting Grant