---
title: "Publications"
---

## 2023

Yang Shen, Angus J. Robertson, Ad Bax. Validation of ensemble and static X-ray crystal structure representations of SARS-CoV2 main protease by solution NMR residual dipolar couplings. *Journal of Molecular Biology*. 435: 11, 168067, 2023. [https://doi.org/10.1016/j.jmb.2023.168067](https://doi.org/10.1016/j.jmb.2023.168067). Access the [MS 📖](resources/papers/14.pdf), [SI 📖](resources/papers/14_SI.pdf).

## 2022

Angus J. Robertson, Jinfa Ying, Ad Bax. NMR Observation of Sylfhydryl Signals in SARS-CoV-2 Main Protease Aids Structural Studies. *ChemBioChem*. e202200471, 2022. [https://doi.org/10.1002/cbic.202200471](https://doi.org/10.1002/cbic.202200471). Access the [MS 📖](resources/papers/13.pdf), [SI 📖](resources/papers/13_SI.pdf).

Angus J. Robertson†, F. Aaron Cruz-Navarrete†, Henry P. Wood, Nikita Vekaria, Andrea M. Hounslow, Claudine Bisson, Matthew J. Cliff, Nicola J. Baxter, and Jonathan P. Waltho. An enzyme with high catalytic proficiency utilizes distal site substrate binding energy to stabilize the closed state but at the expense of substrate inhibition. *ACS catalysis*. 12(5):3149-3164, 2022. [https://doi.org/10.1021/acscatal.1c05524](https://doi.org/10.1021/acscatal.1c05524). Access the [MS 📖](resources/papers/12.pdf), [SI 📖](resources/papers/12_SI.pdf).

## 2021

Altincekic Nadide, Korn Sophie Marianne, Qureshi Nusrat Shahin, Dujardin Marie, Ninot-Pedrosa Martí, Abele Rupert, Abi Saad Marie Jose, Alfano Caterina, Almeida Fabio C. L., Alshamleh Islam, de Amorim Gisele Cardoso, Anderson Thomas K., Anobom Cristiane D., Anorma Chelsea, Bains Jasleen Kaur, Bax Adriaan, Blackledge Martin, Blechar Julius, Böckmann Anja, Brigandat Louis, Bula Anna, Bütikofer Matthias, Camacho-Zarco Aldo R., Carlomagno Teresa, Caruso Icaro Putinhon, Ceylan Betül, Chaikuad Apirat, Chu Feixia, Cole Laura, Crosby Marquise G., de Jesus Vanessa, Dhamotharan Karthikeyan, Felli Isabella C., Ferner Jan, Fleischmann Yanick, Fogeron Marie-Laure, Fourkiotis Nikolaos K., Fuks Christin, Fürtig Boris, Gallo Angelo, Gande Santosh L., Gerez Juan Atilio, Ghosh Dhiman, Gomes-Neto Francisco, Gorbatyuk Oksana, Guseva Serafima, Hacker Carolin, Häfner Sabine, Hao Bing, Hargittay Bruno, Henzler-Wildman K., Hoch Jeffrey C., Hohmann Katharina F., Hutchison Marie T., Jaudzems Kristaps, Jović Katarina, Kaderli Janina, Kalniņš Gints, Kaņepe Iveta, Kirchdoerfer Robert N., Kirkpatrick John, Knapp Stefan, Krishnathas Robin, Kutz Felicitas, zur Lage Susanne, Lambertz Roderick, Lang Andras, Laurents Douglas, Lecoq Lauriane, Linhard Verena, Löhr Frank, Malki Anas, Bessa Luiza Mamigonian, Martin Rachel W., Matzel Tobias, Maurin Damien, McNutt Seth W., Mebus-Antunes Nathane Cunha, Meier Beat H., Meiser Nathalie, Mompeán Miguel, Monaca Elisa, Montserret Roland, Mariño Perez Laura, Moser Celine, Muhle-Goll Claudia, Neves-Martins Thais Cristtina, Ni Xiamonin, Norton-Baker Brenna, Pierattelli Roberta, Pontoriero Letizia, Pustovalova Yulia, Ohlenschläger Oliver, Orts Julien, Da Poian Andrea T., Pyper Dennis J., Richter Christian, Riek Roland, Rienstra Chad M., Robertson Angus, Pinheiro Anderson S., Sabbatella Raffaele, Salvi Nicola, Saxena Krishna, Schulte Linda, Schiavina Marco, Schwalbe Harald, Silber Mara, Almeida Marcius da Silva, Sprague-Piercy Marc A., Spyroulias Georgios A., Sreeramulu Sridhar, Tants Jan-Niklas, Tārs Kaspars, Torres Felix, Töws Sabrina, Treviño Miguel Á., Trucks Sven, Tsika Aikaterini C., Varga Krisztina, Wang Ying, Weber Marco E., Weigand Julia E., Wiedemann Christoph, Wirmer-Bartoschek Julia, Wirtz Martin Maria Alexandra, Zehnder Johannes, Hengesbach Martin, Schlundt Andreas. Large-Scale Recombinant Production of the SARS-CoV-2 Proteome for High-Throughput and Structural Biology Applications. *Frontiers in Molecular Biosciences*, 2021 8:89. [https://doi.org/10.3389/fmolb.2021.653148](https://doi.org/10.3389/fmolb.2021.653148).  Access the [MS 📖](resources/papers/11.pdf), [SI 📖](resources/papers/11_SI.pdf).

Sai Chaitanya Chiliveri, Angus J. Robertson, Yang Shen, Dennis A Torchia, and Ad Bax. Advances in NMR Spectroscopy of Weakly Aligned Biomolecular Systems. *Chemical Reviews*, 122, 10, 9307-9330, 2022. [https://doi.org/10.1021/acs.chemrev.1c00730](https://doi.org/10.1021/acs.chemrev.1c00730). Access the [MS 📖](resources/papers/10.pdf), [SI 📖](resources/papers/10_SI.pdf).

Angus J. Robertson†, Joseph M. Courtney†, Yang Shen, Jinfa Ying, and Ad Bax. Concordance of X-ray and AlphaFold2 Models of SARS-CoV-2 Main Protease with Residual Dipolar Couplings Measured in Solution. *Journal of the American Chemical Society*. 43(46):19306-19310, 2021. [https://doi.org/10.1021/jacs.1c10588](https://doi.org/10.1021/jacs.1c10588). Access the [MS 📖](resources/papers/9.pdf), [SI 📖](resources/papers/9_SI.pdf).

Angus J. Robertson†, Alex L. Wilson†, Matthew J. Burn, Matthew J. Cliff, Paul L. A. Popelier, and Jonathan P. Waltho. The Relationship between Enzyme Conformational Change, Proton Transfer, and Phosphoryl Transfer in beta-Phosphoglucomutase. *ACS Catalysis*, 7:12840–12849, 2021.  [https://doi.org/10.1021/acscatal.1c01389](https://doi.org/10.1021/acscatal.1c01389). Access the [MS 📖](resources/papers/8.pdf), [SI 📖](resources/papers/8_SI.pdf).

Angus J. Robertson, Jinfa Ying, and Ad Bax. Four-dimensional NOE-NOE spectroscopy of SARS-CoV-2 Main Protease to facilitate resonance assignment and structural analysis. *Magnetic Resonance*, 2(1):129–138, 2021. [https://doi.org/10.5194/mr-2-129-2021](https://doi.org/10.5194/mr-2-129-2021). Access the [MS 📖](resources/papers/7.pdf), [SI 📖](resources/papers/7_SI.pdf).

## 2020

Henry. P. Wood, F. Arron. Cruz-Navarrete, Nicola. J. Baxter, Clare. R. Trevitt, Angus J. Robertson, Sam R. Dix, Andrea M. Hounslow, Matthew J. Cliff, and Jon P. Waltho. Allomorphy as a mechanism of post-translational control of enzyme activity. *Nature Communications*, 11(1):5538, 2020.  [https://doi.org/10.1038/s41467-020-19215-9](https://doi.org/10.1038/s41467-020-19215-9). Access the [MS 📖](resources/papers/6.pdf), [SI 📖](resources/papers/6_SI.pdf)


## 2019

C. Ashley Barnes†, Angus J. Robertson†, John. M. Louis, Philip Anfinrud, and Ad Bax. Observation of beta-Amyloid Peptide Oligomerization by Pressure-Jump NMR Spectroscopy. *Journal of the American Chemical Society*, 141(35):13762–13766, 2019. [https://doi.org/10.1021/jacs.9b06970](https://doi.org/10.1021/jacs.9b06970) Access the [MS 📖](resources/papers/5.pdf), [SI 📖](resources/papers/5_SI.pdf)


L. S. Gonzalez-Delgado, H. Walters-Morgan, B. Salamaga, A. J. Robertson, A. M. Hounslow, E. Jagielska, I. Sabala, M. P. Williamson, A. L. Lovering, and S. Mesnage. Two-site recognition of Staphylococcus aureus peptidoglycan by lysostaphin SH3b. *Nature Chemical Biology*, 16(1):24–30, 2020. [https://doi.org/10.1038/s41589-019-0393-4](https://doi.org/10.1038/s41589-019-0393-4) Access the [MS 📖](resources/papers/4.pdf), [SI 📖](resources/papers/4_SI.pdf)

Nate B. P. Adams, Angus J. Robertson, C. Neil Hunter, Andrew Hitchcock, and Claudine Bisson. Phosphite binding by the HtxB periplasmic binding protein depends on the protonation state of the ligand. *Scientific Reports*, 9(1):10231, 2019. [https://doi.org/10.1038/s41598-019-46557-2](https://doi.org/10.1038/s41598-019-46557-2) Access the [MS 📖](resources/papers/3.pdf), [SI 📖](resources/papers/3_SI.pdf)

## 2018

Angus J. Robertson†, Luke A. Johnson†, Nicola J. Baxter, Clare R. Trevitt, Claudine Bisson, Yi Jin, Henry P. Wood, Andrea M. Hounslow, Matthew J. Cliff, G. Michael Blackburn, Matthew W. Bowler, and Jonathan P. Waltho. Van der Waals Contact. between Nucleophile and Transferring Phosphorus Is Insufficient to Achieve Enzyme Transition-State Architecture. *ACS Catalysis*, 8(9):8140–8153, 2018. [https://doi.org/10.1021/acscatal.8b01612](https://doi.org/10.1021/acscatal.8b01612). Access the [MS 📖](resources/papers/1.pdf), [SI 📖](resources/papers/2_SI.pdf)]

G. A. Sutherland, K. J. Grayson, N. B. P. Adams, D. M. J. Mermans, A. S. Jones, A. J. Robertson, D. B. Auman, A. A. Brindley, F. Sterpone, P. Tuffery, P. Derreumaux, P. L. Dutton, C. Robinson, A. Hitchcock, and C. N. Hunter. Probing the quality control mechanism of the Escherichia coli twin-arginine translocase with folding variants of a de novo-designed heme protein. *The Journal of Biological Chemistry*, 293(18):6672–6681, 2018. [https://doi.org/10.1074/jbc.RA117.000880](https://doi.org/10.1074/jbc.RA117.000880). Access the [MS 📖](resources/papers/1.pdf)



